//----------------------------------
//ALERT
//----------------------------------
export const CAMBIAR_ESTADO_ERROR = 'CAMBIAR_ESTADO_ERROR';
export const CAMBIAR_ESTADO_EXITOSO = 'CAMBIAR_ESTADO_EXITOSO';
//INFORMATION
export const INGRESAR_DATO_INFORMATION = 'INGRESAR_DATO_INFORMATION';
export const HABILITAR_QR_CAMERA='HABILITAR_QR_CAMERA';
export const GUARDAR_INFORMACION_CODIGO='GUARDAR_INFORMACION_CODIGO';